export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  LEGISLATIVE_ADMIN = 'LEGISLATIVE_ADMIN',
  MINISTRY_LEGAL_OFFICER = 'MINISTRY_LEGAL_OFFICER',
  DRAFTING_OFFICER = 'DRAFTING_OFFICER',
  REVIEWER = 'REVIEWER',
  COMMITTEE_MEMBER = 'COMMITTEE_MEMBER',
  STAKEHOLDER_MANAGER = 'STAKEHOLDER_MANAGER',
  PUBLIC_CONSULTATION_OFFICER = 'PUBLIC_CONSULTATION_OFFICER',
  AUDITOR = 'AUDITOR',
  VIEWER = 'VIEWER',
}

export enum LegislativeItemType {
  DRAFT_LAW = 'DRAFT_LAW',
  BILL = 'BILL',
  AMENDMENT = 'AMENDMENT',
  REGULATION = 'REGULATION',
  CABINET_DECISION = 'CABINET_DECISION',
  CIRCULAR = 'CIRCULAR',
  POLICY_DRAFT = 'POLICY_DRAFT',
}

export enum LegislativeStatus {
  DRAFTING = 'DRAFTING',
  INTERNAL_REVIEW = 'INTERNAL_REVIEW',
  COMMITTEE_REVIEW = 'COMMITTEE_REVIEW',
  PUBLIC_CONSULTATION = 'PUBLIC_CONSULTATION',
  LEGAL_REVIEW = 'LEGAL_REVIEW',
  APPROVED = 'APPROVED',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum ConfidentialityLevel {
  PUBLIC = 'PUBLIC',
  INTERNAL = 'INTERNAL',
  RESTRICTED = 'RESTRICTED',
  CONFIDENTIAL = 'CONFIDENTIAL',
  TOP_SECRET = 'TOP_SECRET',
}

export enum Priority {
  URGENT = 'URGENT',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum DocumentCategory {
  DRAFT = 'DRAFT',
  FINAL = 'FINAL',
  SUPPORTING = 'SUPPORTING',
  REFERENCE = 'REFERENCE',
  IMPACT_ANALYSIS = 'IMPACT_ANALYSIS',
  COMMITTEE_REPORT = 'COMMITTEE_REPORT',
  CONSULTATION_FEEDBACK = 'CONSULTATION_FEEDBACK',
  LEGAL_OPINION = 'LEGAL_OPINION',
}

export enum AmendmentStatus {
  PROPOSED = 'PROPOSED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  INCORPORATED = 'INCORPORATED',
}

export enum StakeholderType {
  GOVERNMENT_ENTITY = 'GOVERNMENT_ENTITY',
  PRIVATE_SECTOR = 'PRIVATE_SECTOR',
  NGO = 'NGO',
  ACADEMIC = 'ACADEMIC',
  PUBLIC_REPRESENTATIVE = 'PUBLIC_REPRESENTATIVE',
  INDIVIDUAL = 'INDIVIDUAL',
  INTERNATIONAL_ORGANIZATION = 'INTERNATIONAL_ORGANIZATION',
}

export enum ConsultationStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  REVIEWING = 'REVIEWING',
  COMPLETED = 'COMPLETED',
}

export enum NotificationType {
  WORKFLOW_TRANSITION = 'WORKFLOW_TRANSITION',
  REVIEW_REMINDER = 'REVIEW_REMINDER',
  CONSULTATION_DEADLINE = 'CONSULTATION_DEADLINE',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  ASSIGNMENT = 'ASSIGNMENT',
  ESCALATION = 'ESCALATION',
  SYSTEM = 'SYSTEM',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  VIEW = 'VIEW',
  DOWNLOAD = 'DOWNLOAD',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  PUBLISH = 'PUBLISH',
  EXPORT = 'EXPORT',
  TRANSITION = 'TRANSITION',
}
