apiVersion: v1
kind: ConfigMap
metadata:
  name: qanunora-config
  namespace: qanunora
  labels:
    app.kubernetes.io/name: qanunora
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  LOG_LEVEL: "info"
  API_VERSION: "v1"
  CORS_ORIGINS: "https://qanunora.gov"
  THROTTLE_SHORT_TTL: "1000"
  THROTTLE_SHORT_LIMIT: "10"
  THROTTLE_MEDIUM_TTL: "10000"
  THROTTLE_MEDIUM_LIMIT: "50"
  THROTTLE_LONG_TTL: "60000"
  THROTTLE_LONG_LIMIT: "200"
  NEXT_PUBLIC_API_URL: "https://api.qanunora.gov/api/v1"
